/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Reviews;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Restaurant Indiana = new Restaurant("Indiana",4,"200","Yummi");
        Review R1 = new Restaurant(Indiana);
        Indiana.addReview(R1);
        Theater Comedy = new Theater("Comedy","Zakki-chan");
        Review R3 = new Theater(Comedy,4,"Zakki-chan","Great");
        Comedy.addReview(R3);

    }
}
