/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");

    }
    
    @Test
    void roll(){
        Library funUnderTest = new Library();
        int[] testResult = funUnderTest.roll(4);
        assertEquals(4,testResult.length);
    }

    @Test
    void containsDuplicates(){
        Library funUnderTest = new Library();
        int[] arr = {1,2,3,4};
        boolean testResult = funUnderTest.containsDuplicates(arr);
        assertEquals(false,testResult);
    }

    @Test
    void  calculatingAverages(){
        Library classUnderTest = new Library();
        int[] arr = {1,2,3,4,5};
        double testResult = classUnderTest.calculatingAverages(arr);
        assertEquals(3.0,testResult);

    }

    @Test
    void  lowestAverage(){
        Library classUnderTest = new Library();
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
         int[] arr = {55, 54, 60, 53, 59, 57, 61};
        int[] testResult = classUnderTest.lowestAverage(weeklyMonthTemperatures);

        String arr2 = Arrays.toString(arr);
        String arr3 = Arrays.toString(testResult);
        assertEquals(arr2,arr3);

    }

}
