/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;
import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

//    public static void main(String[] args) {
////        int[] arr = {1,2,3,4,5};
////        int[] res = roll(4);
////        String str = Arrays.toString(res);
////        System.out.println(str);
////        System.out.println(containsDuplicates(arr));
////        System.out.println(calculatingAverages(arr));
////
////        int[][] weeklyMonthTemperatures = {
////                {66, 64, 58, 65, 71, 57, 60},
////                {57, 65, 65, 70, 72, 65, 51},
////                {55, 54, 60, 53, 59, 57, 61},
////                {65, 56, 55, 52, 55, 62, 57}
////        };
////
////        int[] result2= lowestAverage(weeklyMonthTemperatures);
////        String str2 = Arrays.toString(result2);
////        System.out.println(str2);
//
//    }
    public  static int[] roll(int n){
        int[] sides = new int[n];
        for (int i = 0; i <sides.length ; i++) {
            Random rn = new Random();
            int answer = rn.nextInt(6) + 1;
            sides[i] = answer;
        }
        return sides;
    }

    public static  boolean containsDuplicates(int[] arr){

        for (int i = 0; i <arr.length ; i++) {
            int count=1;
            for (int j = i+1; j < arr.length; j++) {
                if(arr[i] == arr[j])
                    return true;
            }
        }
        return false;
    }

    public static  double calculatingAverages(int[] arr){
        int sum =0;
        double avg= 0.0f;
        for (int i = 0; i < arr.length; i++) {
            sum += arr[i];
        }
        avg = ((float)sum)/arr.length;
        return avg;
    }

    public static int[] lowestAverage(int[][] arr){
        int rowNum = 0;
//        double[] avgArr = new double[arr.length];
        float flag = (float) 3.402823e+38;
        for (int i = 0; i < arr.length; i++) { //arr.length of 2d is the row
            int sum=0;
            float avg = 0;
            for (int j = 0; j < arr[i].length; j++) {
                sum += arr[i][j];
            }
            avg = (float)sum / arr[i].length;

            if(flag > avg) {
                flag = avg;
                rowNum = i;
            }
        }
        int[] lowAvg =arr[rowNum];
        return lowAvg;
    }

}
