/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Restaurant Jabri = new Restaurant("Jabri",5,"200");

        Review R1 = new Review("Jabri", 4, "200", "Excellent Service", "Renad Khawatreh");
        Jabri.addReview(R1);

        Review R2 = new Review("Jabri", 1, "200", "poor Service", "Maryam Mohammad");
        Jabri.addReview(R2);

        Review R3 = new Review("Jabri", 1, "200", "poor Service", "Maryam Mohammad");
        Jabri.addReview(R3);
    }
}
