/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Please enter your file name with the extend");
        Scanner sn = new Scanner(System.in);
        String path = sn.nextLine();
        javaScriptFile(path);

    }
//
//    public static File createFile(String filename) {
//        File myFile = new File("resources/"+filename);
//        try {
//            if (myFile.createNewFile()) {
//
//                System.out.println("File created in " + myFile.getAbsolutePath());
//                return myFile;
//
//            } else {
//                System.out.println("File already created"+myFile.getAbsolutePath());
//                return myFile;
//            }
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//
//        return myFile;
//    }
//
    public  static String javaScriptFile(String path){

//createFile(path)+""
        File file = new File(path);
        //        File file = new File("resources/gates.js");
        String str = "";
        try (Scanner sc = new Scanner(file)){
            int count=0;

            while (sc.hasNext()){
                String Str = sc.nextLine();
                count++;
                if(!Str.endsWith(";") ){
                    if(Str.endsWith("{") || Str.endsWith("}") ||Str.startsWith("//") || Str.contains("if") || Str.contains("else") || Str.isEmpty() ){
                        continue;
                    }
                    else {
                        System.out.println("Line " + count + ": Missing semicolon.");
                        str += "Line " + count + ": Missing semicolon.\n";
                    }
               }

            }
        } catch(FileNotFoundException fileNotFoundException  ){
            System.out.println(fileNotFoundException.getMessage());
        }
     return str;
    }
}
