/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void RestaurantConstructorTest(){
        Restaurant Jabri = new Restaurant("Jabri",3,"200");
        String str = "Restaurant{name='Jabri', numOfStar=3, price='200$'}";
        assertEquals(str, Jabri.toString());
    }

    @Test void ReviewConstructorTest(){
        Restaurant Jabri = new Restaurant("Jabri",5,"200");
        Review R1 = new Review("Jabri", 4, "200", "Excellent Service", "Renad Khawatreh");
        String str = "Review { name = 'Jabri' Number of Star = '4' Price = '200$', body = 'Excellent Service', author = Renad Khawatreh Total Rate = '3.0'}";
        assertEquals(str, R1.toString());
    }

    @Test void AddReviewTest(){
        Restaurant Jabri = new Restaurant("Jabri",5,"200");
        Review R1 = new Review("Jabri", 4, "200", "Excellent Service", "Renad Khawatreh");
        Jabri.addReview(R1);
        String str = "Review { name = 'Jabri' Number of Star = '4' Price = '200$', body = 'Excellent Service', author = Renad Khawatreh Total Rate = '3.25'}";
        assertEquals(str, R1.toString());
    }

    @Test void Rate(){
        Restaurant Jabri = new Restaurant("Jabri",5,"200");

        Review R1 = new Review("Jabri", 4, "200", "Excellent Service", "Renad Khawatreh");
        Jabri.addReview(R1);

        Review R2 = new Review("Jabri", 1, "200", "poor Service", "Maryam Mohammad");
        Jabri.addReview(R2);

        Review R3 = new Review("Jabri", 1, "200", "poor Service", "Maryam Mohammad");
        Jabri.addReview(R3);

        double str = 1.5625;
        assertEquals(str, Jabri.RateStar);
    }

}
